### ISSUE TITLE
Ajout des typings

### ISSUE THREAD

**Issue by Androz2091** [SimonLeclere/Js-String-Cleaner#2]
Ce serait bien d'ajouter les typings au module 👍

**Comment by SimonLeclere** [comment]
Ouaip j'y avais pensé, et pour discord-starboards aussi mais je sais pas trop encore comment faire --'
J'ai commencé à me renseigner je vais continuer ;)

**Comment by SimonLeclere** [comment]
Hey, j'ai fait ce que je pouvais en suivant un article (j'ai appris plein de choses c'était génial) mais se suis pas vraiment sûr que ce que j'ai fait soit bon pour de la production. 

Tu pourrais regarder un peu la branche [#develop](/SimonLeclere/Js-String-Cleaner/tree/develop) et me dire si ca te semble bon ?

Merci d'avance :)

**Comment by Androz2091** [comment]
Salut, ça me semble bon en regardant rapidement. Donc tu as carrément passé tout le projet sous TypeScript ? ^^
Ce que tu peux faire aussi, en plus, c'est créer un workflow GitHub qui te compile le projet et te le publie automatiquement à chaque release (https://github.com/Androz2091/discord-logs/blob/master/.github/workflows/npm-publish.yml, https://github.com/Androz2091/discord-logs/blob/master/package.json#L14)

**Comment by SimonLeclere** [comment]
Pour l'instant ce que j'ai fait c'est qu'à chaque fois que je fais npm patch et npm publish il crée une nouvelle version, lint et formate tout et publie sur github.

Je sais pas si le workflow sera très utile du coup ?

**Comment by Androz2091** [comment]
C'est déjà bien d'avoir un script npm qui te fait tout d'un coup, mais utiliser un workflow a des avantages supplémentaires (tu sais par exemple que seuls les fichiers sur github seront publiés, alors que parfois tu as des fichiers de tests sur ton ordi qui sont envoyés sur npm sans que tu ne t'en rendes compte, et un workflow te permet de ne pas passer par un terminal, tu fais tout via l'interface de github, c'est plus pratique notamment si tu as des collaborateurs). bref, c'est pas du tout obligatoire et tu peux très bien faire sans, mais si jamais tu as un peu de temps utiliser un workflow est encore mieux :smile:

**Comment by SimonLeclere** [comment]
Dac j'essaierai de mettre ca en place tout à l'heure merci beaucoup :)
