### ISSUE TITLE
L and I character overlap

### ISSUE THREAD

**Issue by tgrekov-mhl** [SimonLeclere/Js-String-Cleaner#4]
I've seen a lot of the replacement characters for L and I being used interchangeably, would you merge a request that adds an option to return two variations of the text, one with the overlap characters converted to L and the other to I?

**Comment by SimonLeclere** [comment]
Hey, can you give an example of text where this is a problem?

**Comment by tgrekov-mhl** [comment]
First example I could think of is in “N𝗅” the second character is substituted as L.
Although if an end user was really worried about this they could also just use regex [il]

**Comment by SimonLeclere** [comment]
Well I think it's a good idea :)
