### ISSUE TITLE
Error with maj 'W'

### ISSUE THREAD

**Issue by paolo754** [SimonLeclere/Js-String-Cleaner#7]
Hello, I detected an error when there is a capital letter ( W ), the module shows a space.

![image](https://user-images.githubusercontent.com/52421988/118131593-04977800-b3ff-11eb-9e57-4a501cbab5ef.jpeg)

**Comment by SimonLeclere** [comment]
Hey, first of all sorry for my late answer, I was in weekend.

After adding a test suite for the alphabet, I see that there are indeed several capital letters missing --', thank you very much for informing me I will fix that :)
If you have other suggestions of characters don't hesitate to tell me via an issue or on my server discord !

Have a nice evening,

Simon

![image](https://user-images.githubusercontent.com/39917969/118377762-9bb32a00-b5cf-11eb-9ef3-043edc50a728.png)

**Comment by SimonLeclere** [comment]
Fixed with https://github.com/SimonLeclere/Js-String-Cleaner/commit/e3a97cc2736d7860871f818cce2ab2a9e7a47b0e :)
